Questão #1

Printe os elementos dos seguintes dois vetores usando apenas um for:

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

Depois, faça o mesmo usando numpy (usando a função nditer) e deixe um comentário sobre a diferença dos dois métodos.

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [2]:
import numpy as np

In [17]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for i in arr.flatten():
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [19]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for i in np.nditer(arr,order='c'):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


Questão #2

Peça para o usuário uma lista com as comidas favoritas dele, depois transforme isso em um objeto numpy. Agora transformado, elimine todas as comidas que começam com uma vogal. Mostre o resultado.

Exemplo:

Entrada: [maçã, uva, morango, melancia, acelga]

Saída: [maçã, morango, melancia]

In [6]:
print("Quais são suas comidas favoritas?")
comidas_favoritas = []

resposta = input("Digite suas comidas favoritas e 'fim' quando terminar.")
while resposta != "fim":
    comidas_favoritas.append(resposta)
    resposta = input("Digite suas comidas favoritas e 'fim' quando terminar.")
    
comidas_favoritas = np.array(comidas_favoritas)

vogais = ["a", 'e','i','o','u']

letras_iniciais = np.char.rjust(comidas_favoritas, 1)
indices_para_excluir = np.where(np.in1d(letras_iniciais, vogais))
comidas_favoritas = np.delete(comidas_favoritas, indices_para_excluir)

print(comidas_favoritas)

Quais são suas comidas favoritas?


Digite suas comidas favoritas e 'fim' quando terminar. maca 
Digite suas comidas favoritas e 'fim' quando terminar. banana
Digite suas comidas favoritas e 'fim' quando terminar. abacate
Digite suas comidas favoritas e 'fim' quando terminar. mimosa
Digite suas comidas favoritas e 'fim' quando terminar. uva
Digite suas comidas favoritas e 'fim' quando terminar. abacate
Digite suas comidas favoritas e 'fim' quando terminar. fim


['maca ' 'banana' 'mimosa']


Questão #3

Imprima a dimensão dos seguintes objetos numpy:

a = np.array(2)

b = np.array([1, 2, 3, 4, 5])

c = np.array([[1, 2, 3], [4, 5, 6]])

d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [5]:
a = np.array(2)
a.shape

()

In [6]:
b = np.array([1, 2, 3, 4, 5])
b.shape

(5,)

In [7]:
c = np.array([[1, 2, 3], [4, 5, 6]])
c.shape

(2, 3)

In [10]:
d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
d.shape

(2, 2, 3)

Questão #4

Transforme o array em uma matriz 4 por 3 utilizando numpy.

arr = [1, 2, 3, 4, 'Amelia, 'Bruna, 'Carolina', 'Débora', True, False, False, True]

Depois, faça o mesmo para uma matriz 3 por 4.

In [8]:
arr = [1, 2, 3, 4, 'Amelia', 'Bruna', 'Carolina', 'Débora', True, False, False, True]
np.resize(arr,(4,3))

array([['1', '2', '3'],
       ['4', 'Amelia', 'Bruna'],
       ['Carolina', 'Débora', 'True'],
       ['False', 'False', 'True']], dtype='<U21')

In [9]:
arr_4_por_3 = np.array(arr).reshape(4, 3)
print(arr_4_por_3)

[['1' '2' '3']
 ['4' 'Amelia' 'Bruna']
 ['Carolina' 'Débora' 'True']
 ['False' 'False' 'True']]


In [28]:
np.resize(arr,(3,4))

array([['1', '2', '3', '4'],
       ['Amelia', 'Bruna', 'Carolina', 'Débora'],
       ['True', 'False', 'False', 'True']], dtype='<U11')

In [ ]:
arr_3_por_4 = np.array(arr).reshape(3, 4)
print(arr_3_por_4)

Questão #5

Transforme o seguinte array em uma matriz 3D 3x3x3:

arr = range(27)

Deixe um comentário explicando o que significa uma matriz 3D.

In [29]:
arr = range(27)
np.resize(arr,(3,3,3))
#Matriz 3d é uma coleção de matrizes 2d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

Questão #6

Tente transformar o seguinte array em uma matriz 3x3x3

arr = [1, 2, 3, 4, 5, 6, 7, 8]

Funciona? Se sim, explique o motivo. Se não, explique o erro.

In [30]:
arr = [1, 2, 3, 4, 5, 6, 7, 8]
np.resize(arr,(3x3x3))

SyntaxError: invalid syntax (<ipython-input-30-9776f8112f6f>, line 2)

Questão #7

Percorra o seguinte array utilizando for encaixado:

arr = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

Agora, percorra o mesmo array utilizando a função nditer de numpy.

In [32]:
arr = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
for i in arr:
    print(i)

[[1, 2], [3, 4]]
[[5, 6], [7, 8]]


In [38]:
arr = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
for i in np.nditer(arr):
    print(i)

(array(1), array(5))
(array(2), array(6))
(array(3), array(7))
(array(4), array(8))


Questão #8

Percorra os indexes do seguinte array utilizando for encaixado:

arr = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

Agora faça o mesmo trabalho utilizando a função ndenumerate.

In [42]:
arr = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
for index in range(len(arr)):
    print(index, arr[index])

0 [[1, 2], [3, 4]]
1 [[5, 6], [7, 8]]


In [43]:
arr = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
for index, arr in enumerate(arr, start=0): 
    print(index,arr)

0 [[1, 2], [3, 4]]
1 [[5, 6], [7, 8]]


Questão #9

Junte os dois seguintes arrays na horizontal:

arr1 = [1, 2, 3]

arr2 = [4, 5, 6]

Depois, os junte verticalmente.

In [46]:
arr1 = [1, 2, 3]

arr2 = [4, 5, 6]

joinedlist = arr1+arr2
joinedlist

[1, 2, 3, 4, 5, 6]

In [48]:
stacked_array = np.vstack((arr1,arr2))
stacked_array

array([[1, 2, 3],
       [4, 5, 6]])

Questão #10

DESAFIO: Utilizando manipulação de arrays, ache os indexes do array cujo valor possua apenas 2 vogais no nome usando numpy.

frutas = ['banana', 'morango, 'uva', 'pitaia', 'abacate', 'abacaxi', 'acerola', 'jenipapo', 'kiwi']

In [11]:
frutas = np.array([
    'banana',
    'morango',
    'uva',
    'pitaia',
    'abacate',
    'abacaxi',
    'acerola',
    'jenipapo',
    'kiwi'
])

vogais = ['a', 'e', 'i', 'o', 'u']

contagens = sum([np.char.count(frutas, vogal) for vogal in vogais])
indices = np.where(contagens == 2)[0]

print(indices)

[2 8]


Questão #11

a) Tranforme o seguinte array 2D em dois arrays 2D:

arr = [[1, 2], [3, 4], [5, 6], [7, 8]]

b) Transforme o seguinte array em três arrays com apenas uma coluna:

arr = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [3]:
arr = [[1, 2], [3, 4], [5, 6], [7, 8]]
newarr = np.array_split(arr,2)
newarr

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]])]

In [5]:
arr = [[1, 2], [3, 4], [5, 6], [7, 8]]
newarr2 = np.array_split(arr,3)
newarr2

[array([[1, 2],
        [3, 4]]),
 array([[5, 6]]),
 array([[7, 8]])]

Questão #12

DESAFIO: Utilizando manipulação de arrays, vamos seguir um conjunto de passos para organizar alguns dados. Teremos nesse seguinte array uma ordem que segue:

[Nome do aluno, idade, 'gênero', signo, altura, nota do 1° semestre, nota do 2° bimestre, se está ou não inscrito no próximo ano da escola, nome do outro aluno, idade do outro aluno...]

arr = ['Amélia', 13, 'F', 'peixes', 1.51, 9, 7, True, 'Bruno', 14, 'O', 'leão', 1.60, 4, 10, False, 'João', 14, 'M', 'escorpião', 1.58, 8, 9, True, 'Jordana', 13, 'F', 'escorpião', 1.72, 9, 9, False]

a) Enumere os indexes de todas as informações que são do tipo string.

b) Separe essas informações do objeto arr de forma que cada aluno tenha seu próprio array.

c) Separe em duas colunas, a primeira com o nome, a idade, o gênero e o signo e a segunda com a altura, nota do primeiro bimestre, nota do segundo bimestre e se está ou não inscrito no próximo ano.

d) Elimine o gênero de todos os arrays cujos alunos tem menos de 14 anos.