In [99]:
import numpy as np
from numpy import pi

Questão #1

Dado o array:

arr = np.arange(50)

Selecione a alternativa INCORRETA na utilização de filtros e máscaras neste Numpy array.

Alternativas

arr_atualizado = arr[arr % 2]

print(arr_atualizado)

arr_atualizado = arr[arr>5]

print(arr_atualizado)

arr_atualizado = arr[arr <= 10]

print(arr_atualizado)

arr_atualizado = arr[(arr != 1) | (arr != 3)]

print(arr_atualizado)

In [4]:
arr = np.arange(50)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [8]:
arr_atualizado = arr[(arr != 1) | (arr != 3)]

print(arr_atualizado)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


Questão #2

Agora, vamos explorar os arrays aleatórios e máscaras. Faça o que se pede:

a) Crie um array aleatório de 15 itens entre 0 e 100;

b) Qual o maior número do array?

c) Qual a sua posição?

d) Verifique quais números do array são maior que 10;

e) Salve em uma nova lista apenas os itens entre 10 e 30.

In [12]:
arr1 = np.random.randint(101, size=15)
arr1

array([33, 58, 69, 34, 19, 33, 73, 85, 82, 64, 93, 15, 53, 53,  4])

In [18]:
np.amax(arr1)

93

In [21]:
np.where(arr1==93)

(array([10], dtype=int64),)

In [22]:
print(arr1[arr1>10])

[33 58 69 34 19 33 73 85 82 64 93 15 53 53]


In [36]:
lista_10_30 = np.where(np.logical_and(arr1>= 10, arr1<= 30))
lista_10_30

(array([ 4, 11], dtype=int64),)

Questão #3

Nosso próximo foco serão as matrizes. Faça o que se pede:

a) Gere uma matriz (3,2) com números linearmente espaçados entre 0 e 100 e intervalos de 20, usando o np.linspace();

b) Gere uma matriz aleatória (5,2) com números entre 0 e 100;

c) Crie um array com as dimensões apropriadas que, quando multiplicado pela matriz do item a), devolva essa mesma matriz. Use o método np.matmul().

In [118]:
rand_int = np.linspace(0,100,6).reshape(3,2)
rand_int

array([[  0.,  20.],
       [ 40.,  60.],
       [ 80., 100.]])

In [108]:
np.random.randint(101, size=(5,2))

array([[68, 38],
       [79, 80],
       [34, 47],
       [85, 71],
       [48,  1]])

In [120]:
array = np.identity(2)
print(array)
print(np.matmul(rand_int, array))

[[1. 0.]
 [0. 1.]]
[[  0.  20.]
 [ 40.  60.]
 [ 80. 100.]]
