In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.options.display.float_format = '{:,.2f}'.format

### Problema 1
Vamos praticar gerar matrizes e fazer operações com as linhas e colunas:

(a) Crie uma matriz A com as dimensões (5, 4) e elementos aleatórios variando entre 0 e 50, com o 50 incluso;

__Dica:__ Utilize as funções `np.random.randint` e `np.reshape`

(b) Retorne a média do vetor

(c) Retorne os menores valores de cada coluna;

(d) Retorne os maiores valores de cada linha.

In [3]:
a = np.random.randint(low=0, high=51, size=(5,4))
print(a)

[[49  4  9  1]
 [42 50 15 39]
 [ 0  1 36 45]
 [32 30 30  1]
 [25 15 39 36]]


In [4]:
a.mean()

24.95

In [5]:
np.min(a[:], axis=0)

array([0, 1, 9, 1])

In [6]:
np.max(a[:], axis=1)

array([49, 50, 45, 32, 39])

### Problema 2

Crie um objeto DataFrame que contenha os dados da tabela abaixo, os quais se referem ao peso, altura e idade de cinco pessoas:


| Peso (kg) | Altura (cm) | Idade (anos) |
|-----------|-------------|--------------|
|  47 | 161	| 31 |
|  80 | 170	| 21 |
|  60 | 175	| 16 |
|  90 | 162	| 28 |
| 100 | 185	| 23 |
| 147 | 189 | 32 |

Com base no DataFrame criado, realize o que for pedido nos itens abaixo:

(a) Visualize apenas os dados da coluna que contém a altura das pessoas;

(b) Obtenha a idade média das pessoas;

(c) Obtenha os dados das pessoas que estão abaixo da altura média;

(d) Crie um nova coluna no DataFrame que contenha o IMC (Índice de Massa Corporal) de cada pessoa;

__Obs.:__ A fórmula para o IMC é dada por IMC = Peso/(Altura)² com o peso em kg e a altura em metros.

(e) Remova a coluna que contém a idade das pessoas;

(f) Crie uma nova coluna chamada Classificação, que contenha a classificação de cada indivíduo, de acordo com o seu IMC. Para isso, consulte a tabela abaixo.

| IMC             | Classificação |
|-----------------|---------------|
Menor que 18,5    | Subpeso |
Entre 18,5 e 24,9 | Normal |
Entre 25,0 e 29,9 | Sobrepeso |
Entre 30,0 e 39,9 | Obesidade Grau I |
Maior que 40,0    | Obesidade Grau II |

(g) Salve esses dados do DataFrame em um arquivo csv.

In [7]:
pessoas = {"Peso(kg)":[47,80,60,90,100,147],
          "Altura(cm)":[161,170,175,162,185,189],
          "Idade(anos)":[31,21,16,28,23,32]} 
pessoas

{'Peso(kg)': [47, 80, 60, 90, 100, 147],
 'Altura(cm)': [161, 170, 175, 162, 185, 189],
 'Idade(anos)': [31, 21, 16, 28, 23, 32]}

In [8]:
df = pd.DataFrame(pessoas)
df

Peso(kg)  Altura(cm)  Idade(anos)
0        47         161           31
1        80         170           21
2        60         175           16
3        90         162           28
4       100         185           23
5       147         189           32

In [9]:
df[['Altura(cm)']]

Altura(cm)
0         161
1         170
2         175
3         162
4         185
5         189

In [10]:
df['Idade(anos)'].mean()

25.166666666666668

In [11]:
df[(df['Idade(anos)']<25.16)]

Peso(kg)  Altura(cm)  Idade(anos)
1        80         170           21
2        60         175           16
4       100         185           23

In [12]:
df_new = df.rename(columns={'Altura(cm)':'Altura(m)'})
df_new

Peso(kg)  Altura(m)  Idade(anos)
0        47        161           31
1        80        170           21
2        60        175           16
3        90        162           28
4       100        185           23
5       147        189           32

In [13]:
df_new['Altura(m)'] = df_new['Altura(m)'].div(10).round(2)
df_new['IMC'] = df_new['Peso(kg)'] / (df_new['Altura(m)']**2)
df_new.head()

Peso(kg)  Altura(m)  Idade(anos)  IMC
0        47      16.10           31 0.18
1        80      17.00           21 0.28
2        60      17.50           16 0.20
3        90      16.20           28 0.34
4       100      18.50           23 0.29

In [14]:
df_new = df_new.drop(columns=['Idade(anos)'])
df_new.head()

Peso(kg)  Altura(m)  IMC
0        47      16.10 0.18
1        80      17.00 0.28
2        60      17.50 0.20
3        90      16.20 0.34
4       100      18.50 0.29

In [15]:
def imc_classificacao(valor):
    if valor['IMC'] <18.5:
        return 'Sobpeso'
    if  (valor['IMC'] >= 18.5) & (valor['IMC'] <=24.9):
        return 'Normal'
    if  (valor['IMC'] >= 25) & (valor['IMC'] <=29.9):
        return 'Sobrepeso'
    if  (valor['IMC'] >= 30.0) & (valor['IMC'] <=39.9):
        return 'Obesidade Grau I'
    if valor['IMC'] >=40.0:
        return 'Obesidade Grau II'

In [16]:
df_new.apply(lambda valor: imc_classificacao(valor), axis=1)
df_new['Classificação'] = df_new.apply(lambda valor: imc_classificacao(valor), axis=1)
df_new

Peso(kg)  Altura(m)  IMC Classificação
0        47      16.10 0.18       Sobpeso
1        80      17.00 0.28       Sobpeso
2        60      17.50 0.20       Sobpeso
3        90      16.20 0.34       Sobpeso
4       100      18.50 0.29       Sobpeso
5       147      18.90 0.41       Sobpeso

In [17]:
df_new.to_csv('df_problema_2.csv')

### Problema 3

O arquivo avocado.xlsx consiste em um dataset que contém dados sobre vendas de abacates  em diversas regiões dos Estados Unidos. Essa dataset contém as seguintes colunas:

| Coluna | Descrição |
|--------|-----------|
| Date | data da observação |
| AveragePrice | preço médio de um único abacate |
| year | ano |
| region | cidade ou região da observação |
| Total Volume | volume total de abacates vendidos |

Além das informações acima, contidas no arquivo avocado.xlsx, o tipo do abacate (convencional ou orgânico) também seria uma informação importante para a sua análise. Suponhamos que você conseguiu essas informações para cada uma das observações do arquivo avocado.csv, na mesma ordem, e salvou-as no arquivo avocado_type.xlsx. Portanto, tudo o que você precisa é juntar esses dois arquivos em um mesmo DataFrame.

Com o DataFrame criado, obtenha o que é solicitado nos itens elencados abaixo:




In [18]:
df1 = pd.read_csv('data/avocado.csv', sep=';')
df2 = pd.read_excel('data/avocado_type.xlsx')

In [19]:
df1.head()

Date  AveragePrice  Total Volume  year  region
0  2015-12-27          1.33     64,236.62  2015  Albany
1  2015-12-20          1.35     54,876.98  2015  Albany
2  2015-12-13          0.93    118,220.22  2015  Albany
3  2015-12-06          1.08     78,992.15  2015  Albany
4  2015-11-29          1.28     51,039.60  2015  Albany

In [20]:
df2.head()

type
0      orgânico
1  convencional
2  convencional
3      orgânico
4      orgânico

In [24]:
df3 = pd.concat([df1,df2],axis=1)
df3

Date  AveragePrice  Total Volume  year            region  \
0      2015-12-27          1.33     64,236.62  2015            Albany   
1      2015-12-20          1.35     54,876.98  2015            Albany   
2      2015-12-13          0.93    118,220.22  2015            Albany   
3      2015-12-06          1.08     78,992.15  2015            Albany   
4      2015-11-29          1.28     51,039.60  2015            Albany   
...           ...           ...           ...   ...               ...   
18244  2018-02-04          1.63     17,074.83  2018  WestTexNewMexico   
18245  2018-01-28          1.71     13,888.04  2018  WestTexNewMexico   
18246  2018-01-21          1.87     13,766.76  2018  WestTexNewMexico   
18247  2018-01-14          1.93     16,205.22  2018  WestTexNewMexico   
18248  2018-01-07          1.62     17,489.58  2018  WestTexNewMexico   

               type  
0          orgânico  
1      convencional  
2      convencional  
3          orgânico  
4          orgânico  
...             ...  
18244  convencional  
18245  convencional  
18246  convencional  
18247  convencional  
18248  convencional  

[18249 rows x 6 columns]

(a) A quantidade de abacates do tipo convecional e do tipo orgânico.

In [26]:
df3['type'].value_counts()

orgânico        9135
convencional    9114
Name: type, dtype: int64


(b) A quantidade de registros (linhas) de abacates vendidos para cada região ordenada da maior venda para a menor.

In [27]:
df3.groupby('region')[['Total Volume']].sum().sort_values("Total Volume", ascending=False)[1:]
# Fist row regarded total US region

Total Volume
region                              
West                1,086,779,155.75
California          1,028,981,653.17
SouthCentral        1,011,279,618.83
Northeast             713,280,909.56
Southeast             615,238,409.11
GreatLakes            589,642,549.29
Midsouth              508,349,357.20
LosAngeles            507,896,547.63
Plains                311,188,529.11
NewYork               240,734,127.53
DallasFtWorth         208,419,286.55
Houston               203,167,867.80
PhoenixTucson         195,643,312.50
WestTexNewMexico      144,521,839.78
Denver                138,902,535.99
SanFrancisco          135,830,191.78
BaltimoreWashington   134,713,919.32
Chicago               133,702,338.51
Portland              110,552,211.60
Seattle               109,214,177.96
MiamiFtLauderdale      97,673,224.03
Boston                 97,273,984.83
SanDiego               89,791,919.69
Atlanta                88,605,118.85
Sacramento             75,163,746.86
Philadelphia           71,838,798.18
NorthernNewEngland     71,532,894.11
Tampa                  66,004,539.31
Detroit                63,422,419.38
SouthCarolina          60,753,772.90
Orlando                58,660,703.89
LasVegas               54,376,906.40
HartfordSpringfield    50,670,537.46
RaleighGreensboro      48,202,731.66
NewOrleansMobile       45,695,136.58
CincinnatiDayton       44,522,007.57
RichmondNorfolk        42,230,851.45
HarrisburgScranton     41,808,858.68
Nashville              35,612,089.23
Charlotte              35,555,544.42
StLouis                32,072,833.33
Indianapolis           30,263,391.43
GrandRapids            30,211,735.93
Columbus               29,993,361.42
Jacksonville           28,790,004.74
Roanoke                25,042,010.81
BuffaloRochester       22,962,470.40
Pittsburgh             18,806,345.81
Louisville             16,097,002.40
Albany                 16,067,799.97
Spokane                15,565,275.48
Boise                  14,413,187.75
Syracuse               10,942,667.68

(c) Para que todos os labels das colunas fiquem padronizados, renomeie aqueles que estão iniciando em letra minúscula para que iniciem em letra maiúscula, trocando espaço por _ e adicionando _ como separação de texto.

In [35]:
df3.columns = df3.columns.str.lower()
df3.rename({'averageprice':'average_price', 'total volume':'total_volume'}, axis=1, inplace=True)
df3.columns = df3.columns.str.title()
df3

Date  Average_Price  Total_Volume  Year            Region  \
0      2015-12-27           1.33     64,236.62  2015            Albany   
1      2015-12-20           1.35     54,876.98  2015            Albany   
2      2015-12-13           0.93    118,220.22  2015            Albany   
3      2015-12-06           1.08     78,992.15  2015            Albany   
4      2015-11-29           1.28     51,039.60  2015            Albany   
...           ...            ...           ...   ...               ...   
18244  2018-02-04           1.63     17,074.83  2018  WestTexNewMexico   
18245  2018-01-28           1.71     13,888.04  2018  WestTexNewMexico   
18246  2018-01-21           1.87     13,766.76  2018  WestTexNewMexico   
18247  2018-01-14           1.93     16,205.22  2018  WestTexNewMexico   
18248  2018-01-07           1.62     17,489.58  2018  WestTexNewMexico   

               Type  
0          orgânico  
1      convencional  
2      convencional  
3          orgânico  
4          orgânico  
...             ...  
18244  convencional  
18245  convencional  
18246  convencional  
18247  convencional  
18248  convencional  

[18249 rows x 6 columns]

(d) Essa dado possui duplicados? Se sim, remova-os do dataset.

In [37]:
df3.duplicated().sum()

0

(e) Retire dos dados a região 'TotalUS'

In [41]:
df3=df3.loc[df3["Region"]!="TotalUS"]

(g) Apresente as regiões que mais venderam abacate em todo o período em ordem decrescente.

In [44]:
df3.groupby("Region")[["Total_Volume"]].sum().sort_values('Total_Volume',ascending=False)

Total_Volume
Region                              
West                1,086,779,155.75
California          1,028,981,653.17
SouthCentral        1,011,279,618.83
Northeast             713,280,909.56
Southeast             615,238,409.11
GreatLakes            589,642,549.29
Midsouth              508,349,357.20
LosAngeles            507,896,547.63
Plains                311,188,529.11
NewYork               240,734,127.53
DallasFtWorth         208,419,286.55
Houston               203,167,867.80
PhoenixTucson         195,643,312.50
WestTexNewMexico      144,521,839.78
Denver                138,902,535.99
SanFrancisco          135,830,191.78
BaltimoreWashington   134,713,919.32
Chicago               133,702,338.51
Portland              110,552,211.60
Seattle               109,214,177.96
MiamiFtLauderdale      97,673,224.03
Boston                 97,273,984.83
SanDiego               89,791,919.69
Atlanta                88,605,118.85
Sacramento             75,163,746.86
Philadelphia           71,838,798.18
NorthernNewEngland     71,532,894.11
Tampa                  66,004,539.31
Detroit                63,422,419.38
SouthCarolina          60,753,772.90
Orlando                58,660,703.89
LasVegas               54,376,906.40
HartfordSpringfield    50,670,537.46
RaleighGreensboro      48,202,731.66
NewOrleansMobile       45,695,136.58
CincinnatiDayton       44,522,007.57
RichmondNorfolk        42,230,851.45
HarrisburgScranton     41,808,858.68
Nashville              35,612,089.23
Charlotte              35,555,544.42
StLouis                32,072,833.33
Indianapolis           30,263,391.43
GrandRapids            30,211,735.93
Columbus               29,993,361.42
Jacksonville           28,790,004.74
Roanoke                25,042,010.81
BuffaloRochester       22,962,470.40
Pittsburgh             18,806,345.81
Louisville             16,097,002.40
Albany                 16,067,799.97
Spokane                15,565,275.48
Boise                  14,413,187.75
Syracuse               10,942,667.68

(h) Calcule o volume total de abacates vendidos para cada tipo e ano.

In [46]:
df3.groupby(["Type","Year"])[["Total_Volume"]].sum()

Total_Volume
Type         Year                 
convencional 2015 1,405,835,526.60
             2016 1,538,913,526.12
             2017 1,505,463,914.14
             2018   433,710,441.83
orgânico     2015 1,322,377,914.02
             2016 1,462,817,222.93
             2017 1,564,148,221.75
             2018   425,395,644.21

(f) existe alguma região que foi a maior responsável pela queda na produção de 2018?

In [49]:
df3.loc[df3["Year"]==2018].groupby('Region')[["Total_Volume"]].sum().sort_values("Total_Volume").head(1)

Total_Volume
Region                
Syracuse  1,046,987.66

(g) Qual cidade menos faturou com a venda de abacates?

In [52]:
df3.groupby("Region")[["Total_Volume"]].sum().sort_values("Total_Volume", ascending=True).head(1)

Total_Volume
Region                
Syracuse 10,942,667.68

### Problema 4

Com base no dataset 'Video_Games_Sales.csv' responda:



(a) Quantos jogos existem em cada genero?


In [53]:
df = pd.read_csv("data/Video_Games_Sales.csv", sep=";")
df

Name Platform  Year_of_Release         Genre  \
0                         Wii Sports      Wii         2,006.00        Sports   
1                  Super Mario Bros.      NES         1,985.00      Platform   
2                     Mario Kart Wii      Wii         2,008.00        Racing   
3                  Wii Sports Resort      Wii         2,009.00        Sports   
4           Pokemon Red/Pokemon Blue       GB         1,996.00  Role-Playing   
...                              ...      ...              ...           ...   
16714  Samurai Warriors: Sanada Maru      PS3         2,016.00        Action   
16715               LMA Manager 2007     X360         2,006.00        Sports   
16716        Haitaka no Psychedelica      PSV         2,016.00     Adventure   
16717               Spirits & Spells      GBA         2,003.00      Platform   
16718            Winning Post 8 2016      PSV         2,016.00    Simulation   

          Publisher  NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales  \
0          Nintendo     41.36     28.96      3.77         8.45         82.53   
1          Nintendo     29.08      3.58      6.81         0.77         40.24   
2          Nintendo     15.68     12.76      3.79         3.29         35.52   
3          Nintendo     15.61     10.93      3.28         2.95         32.77   
4          Nintendo     11.27      8.89     10.22         1.00         31.37   
...             ...       ...       ...       ...          ...           ...   
16714    Tecmo Koei      0.00      0.00      0.01         0.00          0.01   
16715   Codemasters      0.00      0.01      0.00         0.00          0.01   
16716  Idea Factory      0.00      0.00      0.01         0.00          0.01   
16717       Wanadoo      0.01      0.00      0.00         0.00          0.01   
16718    Tecmo Koei      0.00      0.00      0.01         0.00          0.01   

       Critic_Score  Critic_Count  User_Score  User_Count Developer Rating  
0             76.00         51.00        8.00      322.00  Nintendo      E  
1               NaN           NaN         NaN         NaN       NaN    NaN  
2             82.00         73.00        8.30      709.00  Nintendo      E  
3             80.00         73.00        8.00      192.00  Nintendo      E  
4               NaN           NaN         NaN         NaN       NaN    NaN  
...             ...           ...         ...         ...       ...    ...  
16714           NaN           NaN         NaN         NaN       NaN    NaN  
16715           NaN           NaN         NaN         NaN       NaN    NaN  
16716           NaN           NaN         NaN         NaN       NaN    NaN  
16717           NaN           NaN         NaN         NaN       NaN    NaN  
16718           NaN           NaN         NaN         NaN       NaN    NaN  

[16719 rows x 16 columns]

In [54]:
df["Genre"].value_counts()

Action          3370
Sports          2348
Misc            1750
Role-Playing    1500
Shooter         1323
Adventure       1303
Racing          1249
Platform         888
Simulation       874
Fighting         849
Strategy         683
Puzzle           580
Name: Genre, dtype: int64

(b) Temos duplicados nesses dados? E nulos?

In [57]:
df.isna().sum()

Name                  2
Platform              0
Year_of_Release     269
Genre                 2
Publisher            54
NA_Sales              0
EU_Sales              0
JP_Sales              0
Other_Sales           0
Global_Sales          0
Critic_Score       8582
Critic_Count       8582
User_Score         9129
User_Count         9129
Developer          6623
Rating             6769
dtype: int64

(b) Quantos jogos de cada publisher receberam nota acima de 9 na avaliação dos usuarios?

In [60]:
df.loc[df["User_Score"]>9].groupby("Publisher")["Publisher"].count().sort_values()

Publisher
505 Games                              1
LucasArts                              1
Kemco                                  1
Kadokawa Shoten                        1
Jaleco                                 1
Interplay                              1
Infogrames                             1
Ignition Entertainment                 1
GT Interactive                         1
Square                                 1
Square Enix                            1
Destination Software, Inc              1
Codemasters                            1
Sting                                  1
Bethesda Softworks                     1
Sunflowers                             1
Telegames                              1
Activision Value                       1
ValuSoft                               1
Virgin Interactive                     1
Disney Interactive Studios             1
Metro 3D                               1
Microsoft Game Studios                 2
PQube                                  2
Marvel


(c) Faça uma tabela que mostre o total vendido por ano por pais/globalmente de cada publisher? Você consegue observar algum padrão? Com se comportaram as vendas na América do Norte (NA) ao longo do tempo? O mesmo foi visto nos demais lugares? 


In [62]:
df.groupby(["Year_of_Release","Publisher"])[["Global_Sales","NA_Sales","EU_Sales","JP_Sales","Other_Sales"]].sum()

Global_Sales  NA_Sales  \
Year_of_Release Publisher                                              
1,980.00        Activision                            3.02      2.82   
                Atari                                 8.36      7.77   
1,981.00        20th Century Fox Video Games          1.35      1.27   
                Activision                            8.50      7.95   
                Atari                                 8.45      7.87   
...                                                    ...       ...   
2,016.00        Yeti                                  0.02      0.00   
                dramatic create                       0.03      0.00   
2,017.00        Idea Factory                          0.01      0.00   
                Sega                                  0.05      0.00   
2,020.00        Ubisoft                               0.29      0.27   

                                              EU_Sales  JP_Sales  Other_Sales  
Year_of_Release Publisher                                                      
1,980.00        Activision                        0.18      0.00         0.03  
                Atari                             0.49      0.00         0.09  
1,981.00        20th Century Fox Video Games      0.07      0.00         0.01  
                Activision                        0.46      0.00         0.08  
                Atari                             0.47      0.00         0.08  
...                                                ...       ...          ...  
2,016.00        Yeti                              0.00      0.02         0.00  
                dramatic create                   0.00      0.03         0.00  
2,017.00        Idea Factory                      0.00      0.01         0.00  
                Sega                              0.00      0.05         0.00  
2,020.00        Ubisoft                           0.00      0.00         0.02  

[2337 rows x 5 columns]


(d) Qual foi jogo mais vendido na união européia? De que ano ele é e qual a editora?


In [65]:
df.loc[df["EU_Sales"]==df["EU_Sales"].max(),["Year_of_Release", "Publisher", "Name", "EU_Sales"]]

Year_of_Release Publisher        Name  EU_Sales
0         2,006.00  Nintendo  Wii Sports     28.96


(e) Quantos % os generos ['Racing', 'Sports', 'Shooter'] representam na base de dados? 

In [103]:
df["Genre"].value_counts(normalize=True)*100

Action         20.16
Sports         14.05
Misc           10.47
Role-Playing    8.97
Shooter         7.91
Adventure       7.79
Racing          7.47
Platform        5.31
Simulation      5.23
Fighting        5.08
Strategy        4.09
Puzzle          3.47
Name: Genre, dtype: float64

(f) Qual plataforma vendeu menos globalmente? obs: imprimir somente o nome

In [111]:
list(df.groupby("Platform")[["Global_Sales"]].sum().sort_values("Global_Sales", ascending=True).head(1).index)[0]

'PCFX'

### Problema 5
A pasta 'data/datasus' contém informações sobre casos de dengue e tabelas auxiliares. <br>

| Tabela | Conteúdo |
|--------|----------|
| Dengue | Quantidade de casos por município |
| Agua | Quantidade de residências em cada município por tipo o abastecimento de água |
| InstalacoesSanitarias | Quantidade de residências em cada município por tipo de rede de esgoto |
| Pib | PIB per capita de cada município |
| Municipios | Relaciona o id_municipio com seu nome e estado |
| Populacao | Quantidade de pessoas morando em áreas urbanas, rurais e população total por município |
| Sexo | Quantidade de pessoas por sexo em cada município |

(a) Calcular o número de casos de dengue por cada estado apresentando os dados em ordem decrescente.


In [ ]:
df = pd.read_csv

(b) Utilizando o dataset InstalacoesSanitarias.csv, determine o número de pessoas que não possuem meio sanitário algum de descarte de dejetos por estado.

(c) Crie uma coluna com a posição de ranking considerando o PIB. Os maiores PIB devem ter os menores valores de ranking.

(d) Qual o PIB dos 5 municípios com mais casos de dengue e sua posição no ranking?