In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.options.display.float_format = '{:,.2f}'.format

### Problema 1
Vamos praticar gerar matrizes e fazer operações com as linhas e colunas:

(a) Crie uma matriz A com as dimensões (5, 4) e elementos aleatórios variando entre 0 e 50, com o 50 incluso;

__Dica:__ Utilize as funções `np.random.randint` e `np.reshape`

(b) Retorne a média do vetor

(c) Retorne os menores valores de cada coluna;

(d) Retorne os maiores valores de cada linha.

In [3]:
a = np.random.randint(low=0, high=51, size=(5,4))
print(a)

[[42  4 26 47]
 [ 6 45 36  9]
 [37  3 42 30]
 [49 40 35 32]
 [ 0  5 50  6]]


In [4]:
a.mean()

27.2

In [5]:
np.min(a[:], axis=0)

array([ 0,  3, 26,  6])

In [6]:
np.max(a[:], axis=1)

array([47, 45, 42, 49, 50])

### Problema 2

Crie um objeto DataFrame que contenha os dados da tabela abaixo, os quais se referem ao peso, altura e idade de cinco pessoas:


| Peso (kg) | Altura (cm) | Idade (anos) |
|-----------|-------------|--------------|
|  47 | 161	| 31 |
|  80 | 170	| 21 |
|  60 | 175	| 16 |
|  90 | 162	| 28 |
| 100 | 185	| 23 |
| 147 | 189 | 32 |

Com base no DataFrame criado, realize o que for pedido nos itens abaixo:

(a) Visualize apenas os dados da coluna que contém a altura das pessoas;

(b) Obtenha a idade média das pessoas;

(c) Obtenha os dados das pessoas que estão abaixo da altura média;

(d) Crie um nova coluna no DataFrame que contenha o IMC (Índice de Massa Corporal) de cada pessoa;

__Obs.:__ A fórmula para o IMC é dada por IMC = Peso/(Altura)² com o peso em kg e a altura em metros.

(e) Remova a coluna que contém a idade das pessoas;

(f) Crie uma nova coluna chamada Classificação, que contenha a classificação de cada indivíduo, de acordo com o seu IMC. Para isso, consulte a tabela abaixo.

| IMC             | Classificação |
|-----------------|---------------|
Menor que 18,5    | Subpeso |
Entre 18,5 e 24,9 | Normal |
Entre 25,0 e 29,9 | Sobrepeso |
Entre 30,0 e 39,9 | Obesidade Grau I |
Maior que 40,0    | Obesidade Grau II |

(g) Salve esses dados do DataFrame em um arquivo csv.

In [7]:
pessoas = {"Peso(kg)":[47,80,60,90,100,147],
          "Altura(cm)":[161,170,175,162,185,189],
          "Idade(anos)":[31,21,16,28,23,32]} 
pessoas

{'Peso(kg)': [47, 80, 60, 90, 100, 147],
 'Altura(cm)': [161, 170, 175, 162, 185, 189],
 'Idade(anos)': [31, 21, 16, 28, 23, 32]}

In [8]:
df = pd.DataFrame(pessoas)
df

Peso(kg)  Altura(cm)  Idade(anos)
0        47         161           31
1        80         170           21
2        60         175           16
3        90         162           28
4       100         185           23
5       147         189           32

In [9]:
df[['Altura(cm)']]

Altura(cm)
0         161
1         170
2         175
3         162
4         185
5         189

In [10]:
df['Idade(anos)'].mean()

25.166666666666668

In [11]:
df[(df['Idade(anos)']<25.16)]

Peso(kg)  Altura(cm)  Idade(anos)
1        80         170           21
2        60         175           16
4       100         185           23

In [12]:
df_new = df.rename(columns={'Altura(cm)':'Altura(m)'})
df_new

Peso(kg)  Altura(m)  Idade(anos)
0        47        161           31
1        80        170           21
2        60        175           16
3        90        162           28
4       100        185           23
5       147        189           32

In [14]:
df_new['Altura(m)'] = df_new['Altura(m)'].div(10).round(2)
df_new['IMC'] = df_new['Peso(kg)'] / (df_new['Altura(m)']**2)
df_new.head()

Peso(kg)  Altura(m)  Idade(anos)   IMC
0        47       1.61           31 18.13
1        80       1.70           21 27.68
2        60       1.75           16 19.59
3        90       1.62           28 34.29
4       100       1.85           23 29.22

In [16]:
df_new = df_new.drop(columns=['Idade(anos)'])
df_new.head()

Peso(kg)  Altura(m)   IMC
0        47       1.61 18.13
1        80       1.70 27.68
2        60       1.75 19.59
3        90       1.62 34.29
4       100       1.85 29.22

In [40]:
def imc_classificacao(valor):
    if valor['IMC'] <18.5:
        return 'Sobpeso'
    if  (valor['IMC'] >= 18.5) & (valor['IMC'] <=24.9):
        return 'Normal'
    if  (valor['IMC'] >= 25) & (valor['IMC'] <=29.9):
        return 'Sobrepeso'
    if  (valor['IMC'] >= 30.0) & (valor['IMC'] <=39.9):
        return 'Obesidade Grau I'
    if valor['IMC'] >=40.0:
        return 'Obesidade Grau II'

In [41]:
df_new.apply(lambda valor: imc_classificacao(valor), axis=1)
df_new['Classificação'] = df_new.apply(lambda valor: imc_classificacao(valor), axis=1)
df_new

Peso(kg)  Altura(m)   IMC      Classificação
0        47       1.61 18.13            Sobpeso
1        80       1.70 27.68          Sobrepeso
2        60       1.75 19.59             Normal
3        90       1.62 34.29   Obesidade Grau I
4       100       1.85 29.22          Sobrepeso
5       147       1.89 41.15  Obesidade Grau II

In [42]:
df_new.to_csv('df_problema_2.csv')

### Problema 3

O arquivo avocado.xlsx consiste em um dataset que contém dados sobre vendas de abacates  em diversas regiões dos Estados Unidos. Essa dataset contém as seguintes colunas:

| Coluna | Descrição |
|--------|-----------|
| Date | data da observação |
| AveragePrice | preço médio de um único abacate |
| year | ano |
| region | cidade ou região da observação |
| Total Volume | volume total de abacates vendidos |

Além das informações acima, contidas no arquivo avocado.xlsx, o tipo do abacate (convencional ou orgânico) também seria uma informação importante para a sua análise. Suponhamos que você conseguiu essas informações para cada uma das observações do arquivo avocado.csv, na mesma ordem, e salvou-as no arquivo avocado_type.xlsx. Portanto, tudo o que você precisa é juntar esses dois arquivos em um mesmo DataFrame.

Com o DataFrame criado, obtenha o que é solicitado nos itens elencados abaixo:




In [18]:
df1 = pd.read_csv('data/avocado.csv', sep=';')
df2 = pd.read_excel('data/avocado_type.xlsx')

In [19]:
df1.head()

Date  AveragePrice  Total Volume  year  region
0  2015-12-27          1.33     64,236.62  2015  Albany
1  2015-12-20          1.35     54,876.98  2015  Albany
2  2015-12-13          0.93    118,220.22  2015  Albany
3  2015-12-06          1.08     78,992.15  2015  Albany
4  2015-11-29          1.28     51,039.60  2015  Albany

In [14]:
df2.head()

type
0      orgânico
1  convencional
2  convencional
3      orgânico
4      orgânico

(a) A quantidade de abacates do tipo convecional e do tipo orgânico.

In [ ]:
df1.merge(df2[[, how="outer", on="


(b) A quantidade de registros (linhas) de abacates vendidos para cada região ordenada da maior venda para a menor.

(c) Para que todos os labels das colunas fiquem padronizados, renomeie aqueles que estão iniciando em letra minúscula para que iniciem em letra maiúscula, trocando espaço por _ e adicionando _ como separação de texto.

(d) Essa dado possui duplicados? Se sim, remova-os do dataset.

(e) Retire dos dados a região 'TotalUS'

(g) Apresente as regiões que mais venderam abacate em todo o período em ordem decrescente.

(h) Calcule o volume total de abacates vendidos para cada tipo e ano.

(f) existe alguma região que foi a maior responsável pela queda na produção de 2018?

(g) Qual cidade menos faturou com a venda de abacates?

### Problema 4

Com base no dataset 'Video_Games_Sales.csv' responda:



(a) Quantos jogos existem em cada genero?


(b) Temos duplicados nesses dados? E nulos?

(b) Quantos jogos de cada publisher receberam nota acima de 9 na avaliação dos usuarios?


(c) Faça uma tabela que mostre o total vendido por ano por pais/globalmente de cada publisher? Você consegue observar algum padrão? Com se comportaram as vendas na América do Norte (NA) ao longo do tempo? O mesmo foi visto nos demais lugares? 



(d) Qual foi jogo mais vendido na união européia? De que ano ele é e qual a editora?



(e) Quantos % os generos ['Racing', 'Sports', 'Shooter'] representam na base de dados? 

(f) Qual plataforma vendeu menos globalmente? obs: imprimir somente o nome

### Problema 5
A pasta 'data/datasus' contém informações sobre casos de dengue e tabelas auxiliares. <br>

| Tabela | Conteúdo |
|--------|----------|
| Dengue | Quantidade de casos por município |
| Agua | Quantidade de residências em cada município por tipo o abastecimento de água |
| InstalacoesSanitarias | Quantidade de residências em cada município por tipo de rede de esgoto |
| Pib | PIB per capita de cada município |
| Municipios | Relaciona o id_municipio com seu nome e estado |
| Populacao | Quantidade de pessoas morando em áreas urbanas, rurais e população total por município |
| Sexo | Quantidade de pessoas por sexo em cada município |

(a) Calcular o número de casos de dengue por cada estado apresentando os dados em ordem decrescente.


(b) Utilizando o dataset InstalacoesSanitarias.csv, determine o número de pessoas que não possuem meio sanitário algum de descarte de dejetos por estado.

(c) Crie uma coluna com a posição de ranking considerando o PIB. Os maiores PIB devem ter os menores valores de ranking.

(d) Qual o PIB dos 5 municípios com mais casos de dengue e sua posição no ranking?