In [27]:
import numpy as np

How to create an empty and a full NumPy array?

In [13]:
ea = np.empty((3,4), dtype=int)
print('empty array')
print(ea)

empty array
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


https://www.geeksforgeeks.org/python-numpy-practice-exercises-questions-and-solutions/

Create a Numpy array filled with all ones

In [12]:
a = np.ones([3,3], dtype = int)
print("Matrix a : \n", a)

Matrix a : 
 [[1 1 1]
 [1 1 1]
 [1 1 1]]


Check whether a Numpy array contains a specified row

In [ ]:
# create numpy array
arr = numpy.array([[1, 2, 3, 4, 5],
                   [6, 7, 8, 9, 10],
                   [11, 12, 13, 14, 15],
                   [16, 17, 18, 19, 20]
                   ])


How to Remove rows in Numpy array that contains non-numeric values?

In [18]:
# Creating 2X3 2-D Numpy array
n_arr = np.array([[10.5, 22.5, 3.8],
                  [41, np.nan, np.nan]])
  
print("Given array:")
print(n_arr)
  
print("\nRemove all rows containing non-numeric elements")
print(n_arr[~np.isnan(n_arr).any(axis=1)])

Given array:
[[10.5 22.5  3.8]
 [41.   nan  nan]]

Remove all rows containing non-numeric elements
[[10.5 22.5  3.8]]


Find the number of occurrences of a sequence in a NumPy array

In [36]:
arr = np.array([[2, 8, 9, 4], 
                   [9, 4, 9, 4],
                   [4, 5, 9, 7],
                   [2, 9, 4, 3]])
  
# Counting sequence
contador = repr(arr).count("9, 4")
  
# view output
print(contador)

4


Find the most frequent value in a NumPy array

In [37]:
# create array
x = np.array([1,2,3,4,5,1,2,1,1,1])
print("Original array:")
print(x)
  
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[1 2 3 4 5 1 2 1 1 1]
Most frequent value in the above array:
1


POO for loop

In [55]:
my_list = [1,2,3,4,5,6,7,8,9,10]

In [56]:
total = 0
for item in my_list:
    total += item
print(total)

55


In [58]:
product = 1
for i in my_list:
    product*=i
print(product)

3628800


In [59]:
a = ["banana", "apple", "microsoft"]

In [60]:
for element in a:
    print(element)

banana
apple
microsoft


In [63]:
b = [20,10,5]
total = 0
for i in b:
    total += i 
print(total)

35


In [66]:
c = list(range(1,5))
c

[1, 2, 3, 4]

In [70]:
total2 = 0
for i in range(1,5):
    total2 += i
print(total2)

10


In [71]:
list(range(1,8))

[1, 2, 3, 4, 5, 6, 7]

In [72]:
total3 = 0
for i in range(1,8):
    if i % 3 ==0 :
        total3 += i
print(total3)

9


In [73]:
total = 0 
for i in range(1,100):
    if i % 3==0 or i %5 ==0:
        total += i
print(total)


2318


In [75]:
given_list = [7,5,4,4,3,1,-2,-3,-5,-7]

total2 = 0
for i in given_list:
    if i < 0:
        total2 += i
print(total2)

-17
