In [1]:
import numpy as np

How to create an empty and a full NumPy array?

In [2]:
ea = np.empty((3,4), dtype=int)
print('empty array')
print(ea)

empty array
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


Create a Numpy array filled with all ones

In [3]:
a = np.ones([3,3], dtype = int)
print("Matrix a : \n", a)

Matrix a : 
 [[1 1 1]
 [1 1 1]
 [1 1 1]]


Check whether a Numpy array contains a specified row

In [4]:
# create numpy array
arr = numpy.array([[1, 2, 3, 4, 5],
                   [6, 7, 8, 9, 10],
                   [11, 12, 13, 14, 15],
                   [16, 17, 18, 19, 20]
                   ])


NameError: name 'numpy' is not defined

How to Remove rows in Numpy array that contains non-numeric values?

In [ ]:
# Creating 2X3 2-D Numpy array
n_arr = np.array([[10.5, 22.5, 3.8],
                  [41, np.nan, np.nan]])
  
print("Given array:")
print(n_arr)
  
print("\nRemove all rows containing non-numeric elements")
print(n_arr[~np.isnan(n_arr).any(axis=1)])

Find the number of occurrences of a sequence in a NumPy array

In [ ]:
arr = np.array([[2, 8, 9, 4], 
                   [9, 4, 9, 4],
                   [4, 5, 9, 7],
                   [2, 9, 4, 3]])
  
# Counting sequence
contador = repr(arr).count("9, 4")
  
# view output
print(contador)

Find the most frequent value in a NumPy array

In [ ]:
# create array
x = np.array([1,2,3,4,5,1,2,1,1,1])
print("Original array:")
print(x)
  
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

POO for loop

In [ ]:
my_list = [1,2,3,4,5,6,7,8,9,10]

In [ ]:
total = 0
for item in my_list:
    total += item
print(total)

In [ ]:
product = 1
for i in my_list:
    product*=i
print(product)

In [ ]:
a = ["banana", "apple", "microsoft"]

In [ ]:
for element in a:
    print(element)

In [ ]:
b = [20,10,5]
total = 0
for i in b:
    total += i 
print(total)

In [ ]:
c = list(range(1,5))
c

In [ ]:
total2 = 0
for i in range(1,5):
    total2 += i
print(total2)

In [ ]:
list(range(1,8))

In [ ]:
total3 = 0
for i in range(1,8):
    if i % 3 ==0 :
        total3 += i
print(total3)

In [ ]:
total = 0 
for i in range(1,100):
    if i % 3==0 or i %5 ==0:
        total += i
print(total)


In [ ]:
given_list = [7,5,4,4,3,1,-2,-3,-5,-7]

total2 = 0
for i in given_list:
    if i < 0:
        total2 += i
print(total2)

https://www.geeksforgeeks.org/python-numpy-practice-exercises-questions-and-solutions/

In [12]:
arr = np.zeros((1,2,3,4))
gfg = np.moveaxis(arr,0,-1).shape
print(gfg)

(2, 3, 4, 1)


In [13]:
# Making a random array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
 
# By default, give the total number of elements.
print(np.size(arr))

8


In [14]:
# initialising numpy array
ini_array = np.array([1, 2, 3, 6, 4, 5])
 
# using shortcut method to reverse
res = np.flip(ini_array)
 
# printing result
print("final array", str(res))

final array [5 4 6 3 2 1]


In [15]:
# make a matrix with numpy
gfg = np.matrix('[1, 2, 3; 4, 5, 6; 7, 8, 9]')
          
# applying matrix.max() method
geeks = gfg.max()
    
print(geeks)

9


In [18]:
matrix= np.arange(1,10).reshape((3, 3))
  
# Original matrix
print(matrix)
  
# Number of rows and columns of the said matrix
print(matrix.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [21]:
import numpy as np
import sys

lineNum = 0
matrix = []
for line in sys.stdin:
    if lineNum==0:
        m_size = int(line)
    else:
        matrix.append(map(float,line.split()))
    lineNum+=1

print(np.linalg.det(matrix))

LinAlgError: 1-dimensional array given. Array must be at least two-dimensional